config/routes.rb
Rails.application.routes.draw do
  resources :lists, only: [:index, :show, :new, :create, :destroy] do
    resources :bookmarks, only: [:new, :create, :index, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, presence: true,uniqueness: true
  validates :overview, presence: true, allow_blank: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list
  before_action :set_bookmark, only: [:show, :edit, :update, :destroy]

  def index
    @bookmarks = Bookmark.all
  end

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>Votre nouveau bookmark</h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchListTraining2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">
  <h1 class="mb-4">Voici toutes les lists</h1>

  <% @lists.each do |list| %>
    <li><%= list.name %></li>
    <p><%= link_to "Voir la liste", list_path(list), class: "btn btn-primary" %></p>
    <p><%= link_to "Supprimer cette liste", list_path(list), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></p>
  <% end %>
  <p><%= link_to "Créer une nouvelle liste", new_list_path, class: "btn btn-primary mt-4" %></p>
</div>

app/views/lists/new.html.erb
<div class="container">
  <h1>Soumettre votre nouvelle liste</h1>

  <%= simple_form_for @list do |f| %>
    <%= f.input :name %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="container">
  <h1>Voici la liste</h1>
  <h3 class="mb-3"><%= @list.name %></h3>
  <% @list.bookmarks.each do |bookmark| %>
    <p class="mt-3"><%= bookmark.movie.title %></p>
    <%= bookmark.comment %>
    <p><%= image_tag bookmark.movie.poster_url, height: 200, width: 200%></p>
    <p><%= link_to "Supprimer ce bookmark", list_bookmark_path(@list, bookmark) , data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} %><p>
  <% end %>
  <p class="mt-3"><%= link_to "Créer un nouveau bookmark", new_list_bookmark_path(@list), class: "btn btn-primary" %></p>
  <p><%= link_to "Retourner aux listes", lists_path, class: "btn btn-primary" %></p>

</div>

  <%# <p><%= link_to "Voici le bookmark associé", list_bookmarks_path(@list) %>